### PR TITLE
Switch to Nengo Sphinx theme

### PR DESCRIPTION
**Pull request by tbekolay**
This switches the main nengo.ai site to the [Nengo Sphinx theme](https://github.com/nengo/nengo-sphinx-theme), which is a fork of the [Crate sphinx theme](https://crate.io/docs/crate/reference/en/latest/) that @celiasmith recently adapted for use with Nengo docs. In addition to looking nicer, it improves navigation quite a bit by having a top navbar which is shared across all the Nengo pages giving quick access to what people tend to want to see; each project's global toctree is then rendered in the left sidebar, if one exists (for nengo.github.io, only the contributor pages are in the global toctree).

This also contains some of @celiasmith's reorganizations of several pages to adjust the messaging from being clearly academic focused to more product focused.

### CODE REVIEW

**Comment by jgosmann** [comment]
> I also feel that the style of main content could be made to look a little bit slicker, but that will be somewhat subjective, involves a lot of fine-tuning, and I don't have any concrete suggestions right now.

I think I just figured out what the main thing is that I disliked: The font is Arial which I think is fine for short heading or links (as in the top navigation bar), but doesn't work very well for longer texts (which occur in particular in the Nengo SPA documentation). It is also a quite generic and overused font in my opinion. Unfortunately, really sans-serif fonts that work well for longer texts are few and far between. Though, my current favourite is Lato which happens to be the font used in the old theme.

Just my 2 cents ...

**Comment by celiasmith** [comment]
@jgosmann thanks, glad you like it!  this is actually a temporary change while we discuss a lot of design elements with some professional designers.  i agree with most of your comments, and will mention them in our conversations (i suspect the designers will have lots of opinions too).  In particular, I agree about the serif for long documentation, and would like a binder to try the gui out, as well as the alignment in the docs menu.  I suspect the docs menu will change to mostly icons.

@tbekolay is in the process of switching a bunch of the current docs to the new theme, so i suspect he'll do spa during that process (correct me if i'm wrong trevor).

**Comment by jgosmann** [comment]
> we discuss a lot of design elements with some professional designers.

Cool! But also sounds like this might take a while, so it might be best to go ahead with the Nengo SPA release. (It's not much trouble to do another release once the documentation stuff is done anyways.)

**Comment by celiasmith** [comment]
> so it might be best to go ahead with the Nengo SPA release.

Yup for sure, but you can use this theme for the docs for now.  We'll release a different one/update this after those conversations.  Once this PR is in they should make the docs look better and will be deployed across the ecosystem.

**Comment by tbekolay** [comment]
> Yup for sure, but you can use this theme for the docs for now.

To be even more explicit, the intention is for this theme to be used on all Nengo projects ASAP. It is definitely not a perfect theme (there's lots of room for improvement -- PRs to nengo/nengo-sphinx-theme welcome!) but it's definitely an improvement on the current situation, mainly in terms of maintaining a coherent navigation across all Nengo projects. And a big bonus for having the theme be something we maintain is that when we update the theme and make a PyPI release, we can re-build the most recent release commit on TravisCI and the recent changes will be reflected by virtue of the build grabbing the most recent nengo-sphinx-theme release.

I'm going to start switching over the projects I maintain shortly.

**Pull request merged**
