### PR TITLE
Added instructions on running models

### PR DESCRIPTION
**Pull request by tbekolay**
There has been some confusion when users run a notebook example within the Nengo GUI. Hopefully this will help clear it up.

### CODE REVIEW

**Comment by tcstewar** [comment]
Thank you for writing this, @tbekolay!  I changed a bit of the wording (I found it odd to refer to the normal Python script approach as "without the GUI" and "outside of the GUI"), and added explicit references to the two places that we have tutorials.

**Comment by tbekolay** [comment]
The reason I used "outside of the GUI" is because I didn't want to give the impression that the GUI is _not_ Python... since it is, essentially, a specific Python interpreter. The issue with "as a Python script", is that people can use the Jupyter notebook, or any other Python environment, not just as standalone scripts. So, then it's basically "with Nengo GUI" or "with Python" but Nengo GUI is Python, so yeah, I opted for "outside of the GUI", but I see why that sounds weird... would you be OK with "As a Python library" ?

Also, one of these days we have to get you out of the habit of double spacing after periods :)

**Comment by tbekolay** [comment]
Pushed some fixups making the "Python interpreter" change and a few other nitpicks.

**Comment by tcstewar** [comment]
Awesome!  I like the "with a Python interpreter" description.  And sorry about the two-spaces...  that's going to be a much harder habit for me to break than all the other bad coding habits of mine.....

This looks great to me.  Let me know when it's live and I'll get the Nengo GUI error message to point to it.  :)

**Comment by tbekolay** [comment]
[It's live!](https://nengo.github.io/users.html#running-models)

**Comment by celiasmith** [comment]
kewl!

Trevor Bekolay wrote:

**Comment by tcstewar** [comment]
And here's the PR for nengo_gui that links to this

https://github.com/nengo/nengo_gui/pull/889

**Pull request merged**
