### PR TITLE
Overhaul look and feel

### PR DESCRIPTION
**Pull request by krisfrenette**
**Motivation and context:**
Redesigning the Nengo website as per the specs from Fusionbox. This required adapting the given new pages to work with the Jekyll templating and moving our current content into the new design.

This PR is still a WIP and is an interim stage. We will still be adapting the design to work properly with out current content. This will be done in follow up commits.

**Interactions with other PRs:**
None

**How has this been tested?**
Currently it has not been tested thoroughly, but will be before this PR is final

**How long should this take to review?**

- Lengthy (more than 150 lines changed or changes are complicated)

**Where should a reviewer start?**
The reviewer should start by pulling down the PR and running the site. Check for visual issues then move on to the code. This should simplify narrowing the problem areas. For a reference you can compare the new site to the sandbox site provided by fusionbox: http://sandbox.dev.fusionbox.com/nengo/index.html

**Types of changes:**

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that causes existing functionality to change)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] I have run the test suite locally and all tests passed.

This is currently a WIP so at this time none of the above apply.

**Still to do:**

- [x] I have to go through each page and ensure styling, content and copy is all tested and updated
- [x] I have to make a bunch of style changes to make the design fit our content
- [x] I have to fix some page inconsistencies when it comes to the overall design
- [x] I have to find and change some of the images to better suited images for the page
- [x] I have to get the documentation working as expected

### CODE REVIEW

**Comment by tbekolay** [comment]
@krisfrenette I've done my first round of changes, check out 241fd0fc14ad3906cb4c7d1ae3f32193dcc26172 and a1b7548f63274bee2e7ddf42213c81682fb70b01 and let me know what you think.

There are still a few things left to do on the documentation page, which I'll start doing now:

- [ ] Use the logos in the Nengo design repo
- [ ] Reorganize the projects to match the ecosystem image better (and possibly organize through the `_data/projects.yml` file)
- [ ] Fill in the [Links] part for each project (using the badges from the old site)

**Comment by krisfrenette** [comment]
Love the MD files for sure. So much easier to read.

**Comment by krisfrenette** [comment]
Typically on a page you want to only have 1 h1 to denote that it is the main topic semantically. If it makes sense to have multiple h1's on the page, then I am fine with leaving it.

**Comment by tbekolay** [comment]
Okay gotcha! I think there's only one h1 on the index page now.

**Comment by tbekolay** [comment]
OK, I finished filling in the details for the documentation page. I think probably a good next step would be to briefly demo the site (either to team Nengo or to all of ABR) to see if there are any issues uncovered, then we can do a final check / cleanup before merging.

**Comment by krisfrenette** [comment]
I think that is a logical step. I will try and have another look through as well.

**Comment by krisfrenette** [comment]
LGTM!

**Pull request merged**
